services:
  db:
    image: postgres:18.3
    env_file: .env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - 5432:5432

  adminer:
    image: adminer:5.3.0
    ports:
      - 8080:8080

  # recipe-ai:
  #   build: ./recipe-ai
  #   ports:
  #     - "8001:8001"
  #   command: uvicorn main:app --host 0.0.0.0 --port 8001

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - recipe-ai
  #   env_file: .env.dev
  #   environment:
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     AI_SERVICE_URL: http://recipe-ai:8001
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000