import type { Recipe } from "~/types";

export const recipes: Recipe[] = [
  {
    id: 1,
    title: "Lentil Soup with Cumin & Coriander",
    subtitle: "A hearty, warming bowl perfect for any season",
    tags: ["Vegan", "Gluten-Free", "High-Fiber"],
    color: "from-amber-400 to-orange-500",
    emoji: "🍲",
    ingredients: [
      "4 cloves garlic, chopped",
      "1 small yellow onion, minced",
      "4 medium carrots, chopped",
      "4 celery stalks, chopped",
      "3 tbsp olive oil",
      "2 cups green or brown lentils, uncooked (I used brown)",
      "1 tsp cumin",
      "½ tsp coriander",
      "8 cups vegetable broth",
    ],
    instructions: [
      "Preheat the oven to 180 degrees celsius.",
      "Rinse the brown rice and cook according to package instructions.",
      "Heat olive oil in a large pot over medium heat. Sauté onion and garlic until softened.",
      "Add carrots, celery, and cumin. Cook for 3 minutes.",
      "Add lentils and vegetable broth. Bring to a boil.",
      "Reduce heat and simmer for 25–30 minutes until lentils are tender.",
      "Season with salt, pepper, and coriander. Serve warm.",
    ],
  },
  {
    id: 2,
    title: "Chicken Caesar Salad",
    subtitle: "Classic and crisp with homemade dressing",
    tags: ["High-Protein", "Low-Carb"],
    color: "from-green-400 to-emerald-600",
    emoji: "🥗",
    ingredients: [
      "2 chicken breasts, grilled and sliced",
      "1 head romaine lettuce, chopped",
      "50g parmesan cheese, shaved",
      "1 avocado, sliced",
      "Caesar dressing to taste",
      "Croutons (optional)",
    ],
    instructions: [
      "Season and grill chicken breasts until cooked through. Rest and slice.",
      "Wash and chop romaine lettuce into bite-sized pieces.",
      "Toss lettuce with Caesar dressing.",
      "Top with chicken, avocado, parmesan, and croutons.",
      "Serve immediately.",
    ],
  },
  {
    id: 3,
    title: "Spinach & Bacon Omelette",
    subtitle: "Quick, filling, and packed with protein",
    tags: ["Keto", "High-Protein", "Quick"],
    color: "from-yellow-300 to-amber-500",
    emoji: "🍳",
    ingredients: [
      "3 large eggs",
      "2 strips bacon, diced",
      "1 cup fresh spinach",
      "¼ onion, diced",
      "Salt and pepper to taste",
      "1 tbsp butter",
    ],
    instructions: [
      "Cook bacon in a non-stick pan until crispy. Set aside.",
      "In the same pan, sauté onion until translucent.",
      "Add spinach and cook until wilted.",
      "Beat eggs with salt and pepper, pour over vegetables.",
      "Scatter bacon on top. Fold omelette when edges set.",
      "Serve hot.",
    ],
  },
];
