export const sampleRecipe = {
  ingredients_used: ["mushrooms", "cabbage", "soy sauce"],
  recipes: [
    {
      id: 1,
      title: "steamed cabbage and mushrooms",
      ingredients: [
        "2 cups (225g) mushrooms, sliced",
        "1/2 cup (100g) thinly sliced cabbage",
        "1/2 teaspoon salt",
        "1/4 teaspoon pepper",
        "1 clove garlic, minced",
        "1 tablespoon (15ml) soy sauce",
        "1 cup (250ml) water",
      ],
      method: [
        "in a medium bowl, combine mushrooms, cabbage, salt, pepper, garlic, and soy sauce. mix well.",
        "bring water to a boil in a large pot. place the bowl with the mushroom mixture in the pot, cover, and let it simmer for 5 minutes.",
        "stir the mixture once or twice to ensure the mushrooms are cooked evenly.",
        "serve hot and enjoy!",
      ],
      validation: {
        valid: false,
        extra_ingredients: ["1 clove garlic, minced"],
      },
      nutrition: {
        total_weight_g: 863.75,
        recipe_per_100g: {
          calories_kcal: 9.27,
          fat_g: 0.62,
          carbs_g: 5.23,
          protein_g: 2.31,
          fiber_g: 2.59,
          sugar_g: 0.18,
        },
        ingredients_not_found: [],
        ingredients: [
          {
            ingredient: "2 cups (225g) mushrooms, sliced",
            matched_food: "Mushroom, beech",
            data_type: "Foundation",
            per_100g: {
              calories_kcal: 0,
              fat_g: 0.45,
              carbs_g: 6.76,
              protein_g: 2.18,
              fiber_g: 3.14,
              sugar_g: 0,
            },
            found: true,
            error: null,
            weight_g: 480,
          },
          {
            ingredient: "1/2 cup (100g) thinly sliced cabbage",
            matched_food: "Cabbage, kimchi",
            data_type: "SR Legacy",
            per_100g: {
              calories_kcal: 15,
              fat_g: 0.5,
              carbs_g: 2.4,
              protein_g: 1.1,
              fiber_g: 1.6,
              sugar_g: 1.06,
            },
            found: true,
            error: null,
            weight_g: 120,
          },
          {
            ingredient: "1/2 teaspoon salt",
            matched_food: "Butter, stick, salted",
            data_type: "Foundation",
            per_100g: {
              calories_kcal: 0,
              fat_g: 82.2,
              carbs_g: 0,
              protein_g: 0,
              fiber_g: 0,
              sugar_g: 0,
            },
            found: true,
            error: null,
            weight_g: 2.5,
          },
          {
            ingredient: "1/4 teaspoon pepper",
            matched_food: "Pepper, banana, raw",
            data_type: "SR Legacy",
            per_100g: {
              calories_kcal: 27,
              fat_g: 0.45,
              carbs_g: 5.35,
              protein_g: 1.66,
              fiber_g: 3.4,
              sugar_g: 1.95,
            },
            found: true,
            error: null,
            weight_g: 1.25,
          },
          {
            ingredient: "1 clove garlic, minced",
            matched_food: "Garlic, raw",
            data_type: "Foundation",
            per_100g: {
              calories_kcal: 143,
              fat_g: 0.38,
              carbs_g: 28.2,
              protein_g: 6.62,
              fiber_g: 2.7,
              sugar_g: 0,
            },
            found: true,
            error: null,
            weight_g: 5,
          },
          {
            ingredient: "1 tablespoon (15ml) soy sauce",
            matched_food: "Soy sauce made from soy (tamari)",
            data_type: "SR Legacy",
            per_100g: {
              calories_kcal: 60,
              fat_g: 0.1,
              carbs_g: 5.57,
              protein_g: 10.5,
              fiber_g: 0.8,
              sugar_g: 1.7,
            },
            found: true,
            error: null,
            weight_g: 15,
          },
          {
            ingredient: "1 cup (250ml) water",
            matched_food: "Water convolvulus,raw",
            data_type: "SR Legacy",
            per_100g: {
              calories_kcal: 19,
              fat_g: 0.2,
              carbs_g: 3.13,
              protein_g: 2.6,
              fiber_g: 2.1,
              sugar_g: 0,
            },
            found: true,
            error: null,
            weight_g: 240,
          },
        ],
        summary:
          "What a wonderful healthy choice! This steamed cabbage and mushrooms dish is incredibly low in calories, making it ideal for weight management. Its impressive fiber content helps keep you feeling full and supports healthy digestion. Plus, the good amount of protein for a vegetable dish and super low sugar provides stable energy and essential nutrients. This perfectly balanced and nutrient-dense combination is fantastic for your well-being!",
      },
    },
  ],
};
